export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Validation error',
  NAME_LENGTH_MUST_BE_3_TO_100: 'Name length must be from 3 to 100',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_IS_STRING: 'Name must be a string',
  EMAIL_IS_REQUIRED: `Email is required`,
  EMAIL_ALREADY_EXIT: `Email already exit`,
  EMAIL_IS_INVALID: `Email is invaild`,
  EMAIL_LENGTH_MUST_BE_6_TO_255: `Email length must be from 6 to 255`,
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_NOT_STRONG:
    'Password must be at least 6 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol.',
  PASSWORD_LENGTH_MUST_BE_6_255: 'Password length must be from 6 to 255',
  PASSWORD_AND_PASSWORD_CONFIRM_NOT_MATCH: 'Password confirmation does not match password',
  COMFIRM_PASSWORD_IS_REQUIRED: 'Confirm passowrd must be required',
  CONFIRM_PASSWORD_IS_NOT_STRONG:
    'Confirm password must be at least 6 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol.',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_6_255: 'Confirm password lenth must be from 6 to 255',
  DATE_OF_BIRTH_MUST_BE_ISO8601_FORMAT: 'Date of birth must be iso8601 format',
  INCORRECT_EMAIL_OR_PASSWORD: 'Incorrect email or password',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_IS_NOT_EXITS: 'Refresh token is not exits',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid',
  LOGIN_SUCCESS: 'Login user successfully!',
  REGISTER_SUCCESS: 'Register user successfully!',
  LOGOUT_SUCCESS: 'Log out user successfully!',
  GET_ME_SUCCESS: `Get me successfully`,
  LOCATION_MUST_BE_A_STRING: `Location must be a string`,
  WEBSITE_MUST_BE_A_STRING: `Website must be a string`,
  USER_NAME_MUST_BE_A_STRING: `Username must be a string`,
  AVATAR_MUST_BE_A_STRING: 'Avatar must be a string',
  COVER_PHOTO_MUST_BE_A_STRING: `Cover photo must be a string`,
  BIO_MUST_BA_A_STRING: 'Bio must be a string',
  UPDATE_ME_SUCCESS: `Update me sucessfully`,
  GET_PROFILE_SUCCESS: `Get profile successfully`,
  FOLLOW_SUCCESSFULLY: `Follow user successfully`,
}
